### ISSUE TITLE
About the implementation and hyperparameters.

### ISSUE THREAD

**Issue by m-zhirnov** [KU-CVLAB/DirecT2V#2]

**Comment by SusungHong** [comment]
Hi @Murmisov, thank you for reaching out again! For your concerns:

1. The hyperparameter 'm' is fixed at 4 for experiments.
2. 'C_dual' is averaged across the last dimension and is then broadcasted when thresholded to quantile(0.1). This may be necessary for your implementation. However, I don't fully understand what you mean by 'normalization.' In my understanding, the range of a quantile operation doesn't need to be normalized.
3. Exactly. We implemented DirecT2V upon Text2Video-Zero and modified the AttnProcessor and scheduler.

I hope this works well for you.

**Comment by SusungHong** [comment]
Indeed, a large portion of the entries for $C_{\text{dual}}$ is near 0. I remember using quantile(0.1), which is equivalent to 10% of the entries. You might find a better quantile for your experiments. Thanks!
